fix runtime error after upgrading JUnit
JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
  ...
Caused by: org.junit.platform.commons.JUnitException: OutputDirectoryProvider not available; probably due to unaligned versions of the junit-platform-engine and junit-platform-launcher jars on the classpath/module path.